version: '3.9'

services:

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cron:
    build:
      context: .
      dockerfile: Dockerfile_cron
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
